import { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';

import { cookies } from 'next/headers'; 
import ContextProvider from '@/context';

export const metadata: Metadata = {
  title: 'AppKit Example App',
  description: 'Generated by AppKit',
};

const inter = Inter({ subsets: ['latin'] });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesObject = await cookies(); 
  const cookieValue = cookiesObject.get('cookie')?.value || ''; 
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider cookies={cookieValue}>{children}</ContextProvider>
      </body>
    </html>
  );
}